name: server
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dart_frog: ^0.3.0
  db:
    git:
      url: https://github.com/loctt-executionlab/shared_db.git
      ref: main
  postgres: ^2.5.2
  shared:
    git:
      url: https://github.com/loctt-executionlab/shared_domain
      ref: main
  stormberry: ^0.9.2

dev_dependencies:
  build_runner: ^2.3.3
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.1.0
