targets:
  $default:
    builders:
      stormberry:
        generate_for:
          # library that exposes all your table classes
          # modify this if to match your library file
          - lib/src/user/user_model.dart
          - lib/src/food/food_model.dart